#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for pandora/repartitioning
#
# IDENTIFICATION
#    src/backend/pandora/repartitioning/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/pandora/partitioning
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	pandora_partitioning.o \
	pandora_partitioning_delta.o \
	pandora_relation_meta.o \
	pandora_relation_meta_hash.o \
	pandora_relation_meta_file.o \
	pandora_relation_meta_utils.o

include $(top_srcdir)/src/backend/common.mk
