#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for pandora/storage
#
# IDENTIFICATION
#    src/backend/pandora/storage/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/pandora/storage
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	pandora_md.o

include $(top_srcdir)/src/backend/common.mk
