#
# Makefile for the PANDORA module
#
# src/backend/pandora/Makefile
#

subdir = src/backend/pandora
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = template partitioning catalog storage mempart

include $(top_srcdir)/src/backend/common.mk
