#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for pandora/catalog
#
# IDENTIFICATION
#    src/backend/pandora/cataloag/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/pandora/catalog
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	pandora_catalog.o \
	pg_pandora.o \

include $(top_srcdir)/src/backend/common.mk
