#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for pandora/template
#
# IDENTIFICATION
#    src/backend/pandora/template/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/pandora/template
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	test.o

include $(top_srcdir)/src/backend/common.mk
