#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for pandora/mempart
#
# IDENTIFICATION
#    src/backend/pandora/mempart/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/pandora/mempart
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	pandora_mempart.o

include $(top_srcdir)/src/backend/common.mk
